export const DUNGEON_NAMES: Record<number, string> = {
  [-1]: "None",
  1: "Act01",
  2: "Act02",
  3: "Act03",
  9: "Act04",
  6: "Act01Endgame",
  7: "Act02Endgame",
  8: "Act03Endgame",
  10: "Act04Endgame",
  11: "Act01Abyss",
  12: "Act02Abyss",
  13: "Act03Abyss",
  14: "Act04Abyss",
  15: "Act01Oblivion",
  16: "Act02Oblivion",
  17: "Act03Oblivion",
  18: "Act04Oblivion",
  19: "Act01Void",
  20: "Act02Void",
  21: "Act03Void",
  22: "Act04Void",
  23: "T1 Endless Nightmare",
  24: "T5 Endless Nightmare",
  25: "T4 Endless Nightmare",
  26: "T2 Endless Nightmare",
  27: "T3 Endless Nightmare",
  28: "T6 Endless Nightmare",
  29: "T7 Endless Nightmare",
  30: "T8 Endless Nightmare",
  31: "T9 Endless Nightmare",
  32: "T10 Endless Nightmare",
  33: "T11 Endless Nightmare",
  34: "T12 Endless Nightmare",
  35: "T13 Endless Nightmare",
  36: "T14 Endless Nightmare",
  37: "T15 Endless Nightmare",
  38: "T16 Endless Nightmare",
};

export const GAME_OVER_SOURCES = [
  { id: 0, label: "Defeat" },
  { id: 1, label: "Manual Finish" },
  { id: 2, label: "Timer" },
  { id: 3, label: "Completed" },
  { id: 4, label: "Manual Finish With Portal" }
];

export const CURRENCY_MAPPINGS: Record<number, { name: string; texture: string; fragmentTexture?: string }> = {
  0: { name: "Tool of Tinkering", texture: "/textures/IconTool_Tinkering.png" },
  1: { name: "Tool of Enhancement", texture: "/textures/IconTool_Enhancement.png", fragmentTexture: "/textures/IconFragment_Enhancement.png" },
  2: { name: "Greater Tool of Enhancement", texture: "/textures/IconTool_GreaterEnhancement.png", fragmentTexture: "/textures/IconFragment_GreaterEnhancement.png" },
  3: { name: "Tool of Locksmithing", texture: "/textures/IconTool_Locksmithing.png", fragmentTexture: "/textures/IconFragment_Locksmithing.png" },
  4: { name: "Imbued Tool of Fury", texture: "/textures/IconTool_Fury.png", fragmentTexture: "/textures/IconFragment_Fury.png" },
  5: { name: "Imbued Tool of Faith", texture: "/textures/IconTool_Faith.png", fragmentTexture: "/textures/IconFragment_Faith.png" },
  6: { name: "Imbued Tool of Discipline", texture: "/textures/IconTool_Discipline.png", fragmentTexture: "/textures/IconFragment_Discipline.png" },
  7: { name: "Corrupted Tool", texture: "/textures/IconTool_Corrupted.png", fragmentTexture: "/textures/IconFragment_Corrupted.png" },
  8: { name: "Divine Tool", texture: "/textures/IconTool_Divine.png", fragmentTexture: "/textures/IconFragment_Divine.png" },
};